// Meaning Mode example index loader.
// Loads the pre-built example index (generated by build-example-index.mjs).
// The index is derived from .static-export-cache/words.json — never modifies it.

import { MEANING_EXAMPLE_INDEX, getExample, hasExample } from "./example-index.generated.mjs";

/**
 * Get the example sentence for a word by its wordId.
 * Returns null if no example exists.
 */
export function getExampleForWord(wordId) {
  if (!wordId) return null;
  const entry = getExample(wordId);
  if (!entry || !entry.example) return null;
  return {
    sourceWordId: entry.sourceWordId,
    word: entry.word,
    example: entry.example,
    exampleCn: entry.exampleCn || null,
    sourceField: entry.sourceField || "example"
  };
}

/**
 * Check if a word has an example in the index.
 */
export function hasExampleForWord(wordId) {
  return hasExample(wordId);
}

/**
 * Get index statistics.
 */
export function getIndexStats() {
  const entries = Object.keys(MEANING_EXAMPLE_INDEX);
  let withCnCount = 0;
  for (const key of entries) {
    if (MEANING_EXAMPLE_INDEX[key].exampleCn) withCnCount++;
  }
  return {
    total: entries.length,
    withChineseTranslation: withCnCount,
    coverage: entries.length > 0 ? "100%" : "0%"
  };
}

export { MEANING_EXAMPLE_INDEX };